name: Run PSScriptAnalyzer

on:
  push:
    branches: [master]

jobs:
  check:
    name: Run PSScriptAnalyzer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run PSScriptAnalyzer
        uses: devblackops/github-action-psscriptanalyzer@v2.4.0
        with:
          rootPath: .\SyncroRMM
          recurse: true
          settingsPath: PSScriptAnalyzerSettings.psd1
