name: Publish new version
on:
  push:
    tags: '*'

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: PowerShell script
        uses: Amadevus/pwsh-script@v2.0.3
        id: Build-Module
        with:
          script: |
            Install-Module ModuleBuilder -Force
            Build-Module

      - name: Update Metadata
        uses: natescherer/update-powershell-metadata-action@v2
        with:
          path: .\Output\SyncroRMM
          version: ${{ github.ref_name }}
      
      - name: Publish PowerShell Module
        uses: natescherer/publish-powershell-action@v1
        with:
          token: ${{ secrets.PSGALLERYAPIKEY }}
          target: gallery
          path: .\Output\SyncroRMM
